### PR TITLE
feat: add get release tag script

### PR DESCRIPTION
**Pull request by jacoobes**

### CODE REVIEW

**Review by SrIzan10 — CHANGES_REQUESTED** [review]
add it to the json file in the babashka folder (also use the environment variable GH_TOKEN, i don't remember how it was called)

**Comment by jacoobes** [comment]
> add it to the json file in the babashka folder (also use the environment variable GH_TOKEN, i don't rennet how it was called)

is it in the server or is it only in node?

**Comment by SrIzan10** [comment]
it's in a .env file in the root

**Comment by SrIzan10** [comment]
ok so its GHTOKEN in a .env file in the root of the project

**Review by SrIzan10 — CHANGES_REQUESTED** [review]
it's GHTOKEN, not TOKEN.
TOKEN is for request tokens
and GHTOKEN is for a github api request token

**Review by SrIzan10 — APPROVED** [review]
cheers!

**Comment by jacoobes** [comment]
🫡🫡🫡

**Comment by jacoobes** [comment]
Cheers

**Pull request merged**
