### PR TITLE
feedback brought back to v2

### PR DESCRIPTION
**Pull request by SrIzan10**
also update drizzle

### CODE REVIEW

**Review by jacoobes — APPROVED** [review]

**Comment by SrIzan10** [comment]
@sernbot ready to merge

**Comment by SrIzan10** [comment]
what

**Comment by SrIzan10** [comment]
@sernbot ready to merge

**Comment by SrIzan10** [comment]
alright I'm merging myself, looks like I accidentally migrated the database in production :skull:

**Pull request merged**
